CREATE DATABASE IF NOT EXISTS `errand_system_db`;
USE `errand_system_db`;

-- Table for system users (Riders, Dispatchers, Owners/Admins)
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `passwordHash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `firstName` VARCHAR(255) NOT NULL DEFAULT 'User',
  `middleName` VARCHAR(255) NOT NULL DEFAULT '',
  `lastName` VARCHAR(255) NOT NULL DEFAULT 'Account',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(50) NOT NULL DEFAULT '',
  `role` VARCHAR(50) NOT NULL DEFAULT 'RIDER',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dedicated table for Customer App users
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `passwordHash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `firstName` VARCHAR(255) NOT NULL DEFAULT 'Customer',
  `middleName` VARCHAR(255) NOT NULL DEFAULT '',
  `lastName` VARCHAR(255) NOT NULL DEFAULT '',
  `phone` VARCHAR(50) NOT NULL DEFAULT '',
  `address` TEXT NULL,
  `role` VARCHAR(50) NOT NULL DEFAULT 'CUSTOMER',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dedicated table for Pabili Orders only
CREATE TABLE IF NOT EXISTS `pabili_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderId` VARCHAR(100) NOT NULL UNIQUE,
  `customerId` VARCHAR(100) NOT NULL,
  `customerName` VARCHAR(255) NOT NULL,
  `categories` TEXT NOT NULL,
  `items` LONGTEXT NOT NULL,
  `totalPurchaseAmount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `baseFee` DECIMAL(10,2) NOT NULL DEFAULT 70.00,
  `distanceKm` DECIMAL(10,2) NOT NULL DEFAULT 2.50,
  `distanceFee` DECIMAL(10,2) NOT NULL DEFAULT 10.00,
  `commission` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(10,2) NOT NULL,
  `paymentMethod` VARCHAR(50) NOT NULL DEFAULT 'COD',
  `amountPaid` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `deliveryAddress` TEXT NULL,
  `latitude` DECIMAL(10,7) NULL,
  `longitude` DECIMAL(10,7) NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  `dispatcherId` INT NULL DEFAULT NULL,
  `dispatcherName` VARCHAR(255) NULL DEFAULT NULL,
  `riderId` INT NULL DEFAULT NULL,
  `riderName` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dedicated table for 3NF Store Pinpointing per Pabili Order (max 3 stores)
CREATE TABLE IF NOT EXISTS `store_pinpoints` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderId` VARCHAR(100) NOT NULL,
  `storeName` VARCHAR(255) NOT NULL,
  `latitude` DECIMAL(10,7) NOT NULL,
  `longitude` DECIMAL(10,7) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX `idx_orderId` (`orderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

