import React from "react";
import { FileDown, Loader2, X } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogClose, DialogFooter } from "@/components/ui/dialog";

interface DigitalReportReviewModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  reportName: string;
  rangeLabel: string;
  onDownloadPdf: () => void;
  isGenerating?: boolean;
  generateError?: string | null;
  children: React.ReactNode;
}

/**
 * The "Digital Report Review" step from the proposal's report storyboards:
 * preview -> download. Shared across all 6 report types; each view supplies its
 * own summary as children.
 *
 * The action used to be `window.print()`, which — with no print stylesheet
 * anywhere in the app — handed the browser the live dashboard, sidebar and modal
 * backdrop included. The PDF is now built by the server in a fixed format, so
 * what this modal shows is a preview of the FIGURES, not of the document.
 */
export const DigitalReportReviewModal: React.FC<DigitalReportReviewModalProps> = ({
  open,
  onOpenChange,
  reportName,
  rangeLabel,
  onDownloadPdf,
  isGenerating,
  generateError,
  children,
}) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Digital Report Review — {reportName}</DialogTitle>
          <DialogClose className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100">
            <X size={18} />
          </DialogClose>
        </DialogHeader>

        <p className="text-xs text-slate-500 -mt-2">{rangeLabel}</p>

        <div className="max-h-[55vh] overflow-y-auto border border-slate-100 rounded-xl p-4">{children}</div>

        <p className="text-[11px] text-slate-400 -mt-1">
          The PDF is generated by the server in the standard Sugo report format, with the full
          tables and the notes behind each figure.
        </p>

        {generateError && (
          <p className="text-xs text-rose-600 font-medium" role="alert">
            {generateError}
          </p>
        )}

        <DialogFooter className="flex-row gap-3">
          <button
            onClick={() => onOpenChange(false)}
            className="flex-1 py-2.5 rounded-xl border border-slate-200 text-slate-600 text-sm font-semibold hover:bg-slate-50 transition"
          >
            Back
          </button>
          <button
            onClick={onDownloadPdf}
            disabled={isGenerating}
            className="flex-1 py-2.5 rounded-xl bg-[#1E3A5F] hover:bg-[#162D4A] text-white text-sm font-semibold transition flex items-center justify-center gap-2 disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {isGenerating ? <Loader2 size={16} className="animate-spin" /> : <FileDown size={16} />}
            {isGenerating ? "Generating..." : "Download PDF"}
          </button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
